export { HomePage } from './Home';
export { TasksPage } from './Tasks';
export { SchedulePage } from './Schedule';
export { DiaryPage } from './Diary';
export { HabitsPage } from './Habits';
export { RelationsPage } from './Relations';
export { MemoriesPage } from './Memories';
export { SkillsPage } from './Skills';
export { SettingsPage } from './Settings';
